export const KIDS_HARD_PHRASES = [
  // -----------------------------------------------------------------------
  // 1) Direkt "für Kinder" / Zielgruppe / Altersangaben
  // -----------------------------------------------------------------------
  "für kinder",
  "für babys",
  "für baby",
  "für kleinkinder",
  "für kleine kinder",
  "für die kleinen",
  "für die kleinsten",
  "für die kleinsten kinder",
  "kinderfreundlich",
  "kindgerecht",
  "kinder geeignet",
  "für kinder geeignet",
  "kids",
  "kids channel",
  "kids kanal",
  "kinderkanal",
  "kinder channel",
  "children channel",
  "for kids",
  "for children",
  "for toddlers",
  "for babies",
  "kinderspiele",
  "spiel für kinder",
  "spiele für kinder",

  // Altersfreigaben / "Age Range" Schreibweisen
  "ab 0",
  "ab 4",
  "ab 5",
  "ab 6",
  "2+",
  "3+",
  "4+",
  "5+",
  "6+",
  "ages 0",
  "ages 1",
  "ages 2",
  "ages 3",
  "ages 4",
  "ages 5",
  "ages 6",
  "0 years",
  "1 year",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6 years",

  // -----------------------------------------------------------------------
  // 2) Lieder / Reime / Musik für Kinder (sehr stark)
  // -----------------------------------------------------------------------
  "kinderlied",
  "kinderlieder",
  "kinderliedern",
  "kinderreim",
  "kinderreime",
  "kinderreimen",
  "lieder für kinder",
  "lied für kinder",
  "reime für kinder",
  "kindermusik",
  "musik für kinder",
  "mitmachlied",
  "mitmachlieder",
  "bewegungslied",
  "bewegungslieder",
  "sing mit",
  "mitsingen",
  "zum mitsingen",
  "zum mitmachen",
  "kinderlieder deutsch",
  "kinderlieder auf deutsch",
  "deutsche kinderlieder",
  "baby musik",
  "babylied",
  "babylieder",
  "schlaflied",
  "schlaflieder",
  "wiegenlied",
  "wiegenlieder",

  // Englisch sehr häufig
  "nursery rhyme",
  "nursery rhymes",
  "kids songs",
  "children songs",
  "baby songs",
  "lullaby",
  "lullabies",
  "kids music",
  "songs for kids",
  "songs for children",
  "sing along",
  "singalong",
  "learn song",
  "abc song",
  "alphabet song",
  "numbers song",
  "colors song",
  "shapes song",

  // "Compilation" typisch bei Kids-Liedern
  "kinderlieder compilation",
  "nursery rhymes compilation",
  "kids songs compilation",
  "best of kids songs",

  // -----------------------------------------------------------------------
  // 3) Lernen / Vorschule / Kindergarten (stark)
  // -----------------------------------------------------------------------
  "vorschule",
  "vorschulalter",
  "vorschulkinder",
  "kindergarten",
  "kita",
  "krippe",
  "preschool",
  "pre school",
  "pre-school",
  "toddlers",
  "toddler",
  "kleinkind",
  "kleinkinder",
  "baby lernen",
  "lernen für kinder",
  "lernvideos für kinder",
  "lernvideo für kinder",
  "lernen mit kindern",
  "lernen mit kinder",
  "spielerisch lernen",
  "spielerisch lernen für kinder",
  "abc lernen",
  "alphabet lernen",
  "buchstaben lernen",
  "lesen lernen",
  "schreiben lernen",
  "zahlen lernen",
  "zählen lernen",
  "rechnen lernen",
  "mathe für kinder",
  "farben lernen",
  "formen lernen",
  "tiere lernen",
  "uhr lernen",
  "englisch lernen für kinder",
  "deutsch lernen für kinder",
  "vokabeln für kinder",
  "grundschule",
  "1. klasse",
  "2. klasse",
  "3. klasse",
  "4. klasse",
  "primary school",

  // -----------------------------------------------------------------------
  // 4) Geschichten / Märchen / Gute Nacht (stark)
  // -----------------------------------------------------------------------
  "märchen",
  "märchen für kinder",
  "märchenstunde",
  "kindergeschichte",
  "kindergeschichten",
  "gute nacht geschichte",
  "gute nacht geschichten",
  "gutenachtgeschichte",
  "gutenachtgeschichten",
  "vorlesen für kinder",
  "vorlesen",
  "geschichten für kinder",
  "kinderbuch",
  "kinderbücher",
  "bedtime story",
  "bedtime stories",
  "stories for kids",
  "fairy tale",
  "fairy tales",
  "storytime",
  "kids story",

  // -----------------------------------------------------------------------
  // 5) Spielzeug / Unboxing / Überraschung (stark, aber teils auch Sammler)
  // -----------------------------------------------------------------------
  "spielzeug",
  "spielzeuge",
  "spielzeugvideo",
  "spielzeug videos",
  "spielzeug unboxing",
  "unboxing spielzeug",
  "toy unboxing",
  "toys unboxing",
  "toy review",
  "toys review",
  "surprise toy",
  "surprise toys",
  "überraschungsei",
  "überraschungseier",
  "kinder überraschung",
  "kinderüberraschung",
  "surprise egg",
  "surprise eggs",
  "blind bag",
  "blind bags",
  "unboxing für kinder",
  "spielzeug für kinder",
  "toys for kids",

  // -----------------------------------------------------------------------
  // 6) Basteln / Malen / Ausmalen (meist kids)
  // -----------------------------------------------------------------------
  "ausmalen",
  "ausmalbilder",
  "ausmalbild",
  "malvorlage",
  "malvorlagen",
  "malen für kinder",
  "zeichnen für kinder",
  "basteln für kinder",
  "basteln mit kindern",
  "bastelideen für kinder",
  "kinder basteln",
  "kinderbasteln",
  "kneten",
  "knete",
  "playdough",
  "play dough",

  // -----------------------------------------------------------------------
  // 7) Cartoons / Animation / Zeichentrick (stark)
  // -----------------------------------------------------------------------
  "zeichentrick",
  "zeichentrick für kinder",
  "cartoon",
  "cartoons",
  "cartoon für kinder",
  "cartoons für kinder",
  "kids cartoon",
  "kids cartoons",
  "animation für kinder",
  "animated for kids",

  // Kids-typische Videobegriffe
  "ganze folge",
  "ganze folgen",
  "full episode",
  "full episodes",
  "compilation",
  "kids compilation",
  "nursery compilation",

  // -----------------------------------------------------------------------
  // 8) Kinder-Formate / Hinweise
  // -----------------------------------------------------------------------
  "für kinder erklärt",
  "leicht erklärt für kinder",
  "kinderleicht erklärt",
  "kinder edition",
  "kids edition",
  "für die ganze familie", // nicht 100% kids, aber häufig Familien/Kinder
  "familienkanal", // nicht 100% kids
  "family friendly", // nicht 100% kids

  // -----------------------------------------------------------------------
  // 9) Typische "Kinderwelt"-Wörter (teils nicht 100%, aber sehr häufig)
  // -----------------------------------------------------------------------
  "spiel und spaß",
  "spaß für kinder",
  "spielspaß",
  "kinderspaß",
  "kinder spaß",
  "kinderparty",
  "kindergeburtstag",
  "mit kindern",
  "mit kind",
  "mama und kind",
  "papa und kind",
  "eltern und kinder",

  // -----------------------------------------------------------------------
  // 10) International sehr gängige Kids-Begriffe
  // -----------------------------------------------------------------------
  "kids tv",
  "kids videos",
  "videos for kids",
  "children videos",
  "baby videos",
  "toddler videos",
  "learn with kids",
  "learning for kids",
];
