// lib/config/blockedPhrasesArrayCombatSports.js
// ESM Export wie deine anderen Config-Files

export const COMBAT_SPORTS_PHRASES = [
  // Deutsch allgemein
  "kampfsport",
  "kampf sport",
  "kampfsportler",
  "kampfkunst",
  "kampfkun",
  "kampftraining",
  "sparring",
  "sparren",
  "sparringpartner",
  "ring",
  "octagon",
  "cage",
  "fight",
  "fighter",
  "fightnight",
  "kampf",
  "ko",
  "k.o",
  "knockout",
  "tko",
  "submission",
  "tapout",
  "tap out",

  // MMA / Grappling
  "mma",
  "mixed martial arts",
  "ufc",
  "bellator",
  "one championship",
  "pfl",
  "fight camp",
  "grappling",
  "wrestling",
  "ringer",
  "takedown",
  "double leg",
  "single leg",
  "ground and pound",
  "gnp",
  "clinche",
  "clinch",

  // BJJ / Jiu-Jitsu
  "bjj",
  "jiu jitsu",
  "jiu-jitsu",
  "brasilian jiu jitsu",
  "brazilian jiu jitsu",
  "nogi",
  "no-gi",
  "gi",
  "guard",
  "pass guard",
  "mount",
  "back mount",
  "rear naked choke",
  "rnc",
  "armbar",
  "arm bar",
  "triangle choke",
  "kimura",
  "americana",
  "heel hook",
  "ankle lock",

  // Striking
  "boxen",
  "boxing",
  "kickboxen",
  "kickboxing",
  "k-1",
  "muay thai",
  "muay-thai",
  "muaythai",
  "thaiboxen",
  "thai boxing",
  "savate",
  "taekwondo",
  "tkd",
  "karate",
  "judo",
  "aikido",
  "kung fu",
  "wushu",
  "krav maga",
  "krav-maga",

  // Training / Gear / Moves
  "pratze",
  "pratzen",
  "pads",
  "mitts",
  "heavy bag",
  "punching bag",
  "boxsack",
  "boxsacktraining",
  "shadowboxing",
  "shadow boxing",
  "jab",
  "cross",
  "hook",
  "uppercut",
  "lowkick",
  "low kick",
  "highkick",
  "high kick",
  "elbow",
  "knee strike",
  "knee",
  "headkick",
  "head kick",
];
