// lib/config/blockedPhrasesArrayAddiction.js

export const ADDICTION_HARD_PHRASES = [
  // Allgemein Sucht / Hilfe / Recovery
  "sucht",
  "süchtig",
  "abhängigkeit",
  "abhängig",
  "substanzkonsumstörung",
  "suchtberatung",
  "suchtberater",
  "beratungsstelle",
  "hilfe bei sucht",
  "hilfe bei abhängigkeit",
  "recovery",
  "recovering",
  "genesung",
  "heilung",
  "nüchtern",
  "nüchtern bleiben",
  "abstinenz",
  "abstinent",
  "clean",
  "clean werden",
  "clean bleiben",
  "sobriety",
  "sober",
  "rückfall",
  "rückfallprävention",
  "relapse",
  "craving",
  "verlangen",
  "suchtdruck",
  "entzug",
  "entzugserscheinungen",
  "withdrawal",
  "kaltentzug",
  "entgiftung",
  "detox",
  "entwöhnung",
  "entwöhnungsklinik",
  "rehab",
  "reha",
  "suchttherapie",
  "therapie",
  "stationär",
  "ambulant",
  "klinikum",
  "klinik",
  "tagesklinik",
  "selbsthilfe",
  "selbsthilfegruppe",
  "12 schritte",
  "zwölf schritte",
  "meeting",
  "gruppenmeeting",

  // Bekannte Gruppen / Programme
  "anonyme alkoholiker",
  "aa",
  "aa meeting",
  "aa-meeting",
  "anonyme narkotiker",
  "na",
  "na meeting",
  "na-meeting",

  // Alkohol
  "alkohol",
  "alkoholsucht",
  "alkoholabhängigkeit",
  "alkoholiker",
  "trinksucht",
  "trinkproblem",
  "kater",
  "rausch",
  "saufdruck",
  "trocken",
  "trocken bleiben",
  "rückfall alkohol",
  "alkoholfrei",
  "entzug alkohol",
  "delir",
  "delirium",

  // Cannabis
  "cannabis",
  "gras",
  "weed",
  "thc",
  "kiffen",
  "kiffersucht",
  "cannabissucht",
  "entzug cannabis",
  "pause vom kiffen",

  // Stimulanzien
  "kokain",
  "coke",
  "crack",
  "meth",
  "crystal",
  "crystal meth",
  "kristall",
  "amphetamin",
  "amphetamin-sucht",
  "speed",
  "pepp",
  "ecstasy",
  "mdma",
  "stimulanzien",
  "entzug kokain",
  "entzug meth",

  // Opioide/Opiate + Substitution
  "opioid",
  "opioide",
  "opiat",
  "opiaten",
  "heroin",
  "h",
  "fentanyl",
  "oxycodon",
  "oxy",
  "tilidin",
  "tramadol",
  "codein",
  "substitution",
  "substitutionsprogramm",
  "methadon",
  "buprenorphin",
  "subutex",
  "suboxone",
  "entzug opiat",
  "entzug opioid",

  // Beruhigungsmittel / Benzos
  "benzo",
  "benzos",
  "benzodiazepin",
  "benzodiazepine",
  "diazepam",
  "lorazepam",
  "alprazolam",
  "xanax",
  "tavor",
  "entzug benzo",
  "benzoentzug",

  // Halluzinogene / Sonstiges (vorsichtig, aber oft in Recovery-Kontext)
  "lsd",
  "pilze",
  "psilocybin",
  "ketamin",
  "dissos",
  "trip",
  "polytox",
  "polytoxikomanie",
  "mischkonsum",

  // Typische Recovery-/Therapiebegriffe
  "trigger",
  "triggerwarnung",
  "co-abhängigkeit",
  "coabhängigkeit",
  "scham",
  "schuldgefühle",
  "depression nach entzug",
  "angst nach entzug",
  "suchtgedächtnis",
  "routinen ändern",
  "verhaltenstherapie",
  "achtsamkeit",
  "rückfallanalyse",
  "tagebuch",
  "tagebuch nüchtern",
  "nüchternheit",
];
